<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Event;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Support\Str;

class EventSeeder extends Seeder
{
    public function run()
    {
        // Get admin user for created_by field
        $adminUser = User::where('email', 'admin@diantara.com')->first();
        if (!$adminUser) {
            $adminUser = User::first(); // fallback to first user
        }
        
        $events = [
            [
                'title' => 'Workshop Laravel untuk Pemula',
                'slug' => Str::slug('Workshop Laravel untuk Pemula'),
                'description' => 'Belajar dasar-dasar Laravel framework dari nol hingga mahir. Workshop ini cocok untuk pemula yang ingin memulai karir sebagai web developer.',
                'event_date' => Carbon::now()->addDays(5)->format('Y-m-d'),
                'event_time' => '09:00:00',
                'location' => 'Aula Utama Kampus',
                'capacity' => 50,
                'price' => 0, // FREE
                'created_by' => $adminUser->id ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Seminar Digital Marketing 2024',
                'slug' => Str::slug('Seminar Digital Marketing 2024'),
                'description' => 'Pelajari strategi digital marketing terkini untuk meningkatkan bisnis Anda di era digital. Pembicara dari praktisi berpengalaman.',
                'event_date' => Carbon::now()->addDays(10)->format('Y-m-d'),
                'event_time' => '13:00:00',
                'location' => 'Hotel Grand Ballroom',
                'capacity' => 100,
                'price' => 302000,
                'status' => 'published',
                'approved_by' => $adminUser->id ?? 1,
                'approved_at' => now(),
                'created_by' => $adminUser->id ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Kompetisi Programming Contest',
                'slug' => Str::slug('Kompetisi Programming Contest'),
                'description' => 'Kompetisi programming untuk mahasiswa se-Indonesia. Hadiah total 50 juta rupiah untuk para pemenang.',
                'event_date' => Carbon::now()->addDays(15)->format('Y-m-d'),
                'event_time' => '08:00:00',
                'location' => 'Lab Komputer Gedung A',
                'capacity' => 30,
                'status' => 'published',
                'approved_by' => $adminUser->id ?? 1,
                'approved_at' => now(),
                'created_by' => $adminUser->id ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Webinar UI/UX Design Trends',
                'slug' => Str::slug('Webinar UI/UX Design Trends'),
                'description' => 'Diskusi tentang tren terbaru dalam desain UI/UX dan bagaimana menerapkannya dalam proyek nyata.',
                'event_date' => Carbon::now()->addDays(7)->format('Y-m-d'),
                'event_time' => '19:00:00',
                'location' => 'Online via Zoom',
                'capacity' => 200,
                'price' => 0, // FREE
                'status' => 'published',
                'approved_by' => $adminUser->id ?? 1,
                'approved_at' => now(),
                'created_by' => $adminUser->id ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Bootcamp React Native',
                'slug' => Str::slug('Bootcamp React Native'),
                'description' => 'Intensive bootcamp untuk belajar React Native dalam 3 hari. Dari basic hingga deploy aplikasi ke Play Store.',
                'event_date' => Carbon::now()->addDays(20)->format('Y-m-d'),
                'event_time' => '09:00:00',
                'location' => 'Ruang Training Center',
                'capacity' => 25,
                'status' => 'published',
                'approved_by' => $adminUser->id ?? 1,
                'approved_at' => now(),
                'created_by' => $adminUser->id ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Tech Talk: AI & Machine Learning',
                'slug' => Str::slug('Tech Talk: AI & Machine Learning'),
                'description' => 'Pembahasan mendalam tentang perkembangan AI dan Machine Learning serta implementasinya dalam industri.',
                'event_date' => Carbon::now()->addDays(3)->format('Y-m-d'),
                'event_time' => '15:30:00',
                'location' => 'Auditorium Kampus',
                'capacity' => 150,
                'price' => 0, // FREE
                'status' => 'published',
                'approved_by' => $adminUser->id ?? 1,
                'approved_at' => now(),
                'created_by' => $adminUser->id ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'SCREAM OK DANCE 2025',
                'slug' => Str::slug('SCREAM OK DANCE 2025'),
                'description' => 'Kompetisi dance terbesar tahun ini dengan hadiah jutaan rupiah. Daftarkan tim dance terbaikmu!',
                'event_date' => Carbon::now()->addDays(12)->format('Y-m-d'),
                'event_time' => '18:00:00',
                'location' => 'Jakarta Convention Center',
                'capacity' => 500,
                'created_by' => $adminUser->id ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'BERISIK ASIK Music Festival',
                'slug' => Str::slug('BERISIK ASIK Music Festival'),
                'description' => 'Festival musik dengan lineup artis ternama Indonesia. Nikmati pengalaman musik yang tak terlupakan!',
                'event_date' => Carbon::now()->addDays(25)->format('Y-m-d'),
                'event_time' => '16:00:00',
                'location' => 'Gelora Bung Karno Stadium',
                'capacity' => 10000,
                'created_by' => $adminUser->id ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'SUCI FEST 2025',
                'slug' => Str::slug('SUCI FEST 2025'),
                'description' => 'Stand Up Comedy Indonesia Festival dengan komika terbaik tanah air. Siap-siap ketawa sampai perut sakit!',
                'event_date' => Carbon::now()->addDays(18)->format('Y-m-d'),
                'event_time' => '20:00:00',
                'location' => 'Balai Sarbini Jakarta',
                'capacity' => 800,
                'status' => 'published',
                'approved_by' => $adminUser->id ?? 1,
                'approved_at' => now(),
                'created_by' => $adminUser->id ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Disney THE LITTLE MERMAID JR',
                'slug' => Str::slug('Disney THE LITTLE MERMAID JR'),
                'description' => 'Pertunjukan musikal Disney yang memukau untuk seluruh keluarga. Saksikan petualangan Ariel di bawah laut!',
                'event_date' => Carbon::now()->addDays(8)->format('Y-m-d'),
                'event_time' => '15:00:00',
                'location' => 'Teater Jakarta',
                'capacity' => 300,
                'price' => 0, // FREE
                'status' => 'published',
                'approved_by' => $adminUser->id ?? 1,
                'approved_at' => now(),
                'created_by' => $adminUser->id ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'COOKING COMPETITION',
                'slug' => Str::slug('COOKING COMPETITION'),
                'description' => 'Kompetisi memasak dengan chef-chef profesional sebagai juri. Tunjukkan kreativitas kuliner terbaikmu!',
                'event_date' => Carbon::now()->addDays(14)->format('Y-m-d'),
                'event_time' => '10:00:00',
                'location' => 'Culinary Studio Jakarta',
                'capacity' => 50,
                'status' => 'published',
                'approved_by' => $adminUser->id ?? 1,
                'approved_at' => now(),
                'created_by' => $adminUser->id ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'FESTIVAL KULINER NUSANTARA',
                'slug' => Str::slug('FESTIVAL KULINER NUSANTARA'),
                'description' => 'Nikmati kelezatan kuliner tradisional dari seluruh Nusantara. Ratusan booth makanan dan minuman khas daerah!',
                'event_date' => Carbon::now()->addDays(22)->format('Y-m-d'),
                'event_time' => '11:00:00',
                'location' => 'Lapangan Monas',
                'capacity' => 5000,
                'price' => 0, // FREE
                'status' => 'published',
                'approved_by' => $adminUser->id ?? 1,
                'approved_at' => now(),
                'created_by' => $adminUser->id ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ROBOTICS COMPETITION',
                'slug' => Str::slug('ROBOTICS COMPETITION'),
                'description' => 'Kompetisi robotika tingkat nasional untuk pelajar dan mahasiswa. Hadiah total 100 juta rupiah!',
                'event_date' => Carbon::now()->addDays(30)->format('Y-m-d'),
                'event_time' => '08:00:00',
                'location' => 'Universitas Indonesia',
                'capacity' => 100,
                'status' => 'published',
                'approved_by' => $adminUser->id ?? 1,
                'approved_at' => now(),
                'created_by' => $adminUser->id ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'FESTIVAL BUDAYA BALI',
                'slug' => Str::slug('FESTIVAL BUDAYA BALI'),
                'description' => 'Rayakan kekayaan budaya Bali dengan tarian, musik gamelan, dan upacara adat yang memukau.',
                'event_date' => Carbon::now()->addDays(35)->format('Y-m-d'),
                'event_time' => '16:00:00',
                'location' => 'Pura Besakih, Bali',
                'capacity' => 2000,
                'status' => 'published',
                'approved_by' => $adminUser->id ?? 1,
                'approved_at' => now(),
                'created_by' => $adminUser->id ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'GAMING COMPETITION 2025',
                'slug' => Str::slug('GAMING COMPETITION 2025'),
                'description' => 'Turnamen e-sports terbesar tahun ini. Mobile Legends, PUBG, dan Valorant. Total hadiah 500 juta!',
                'event_date' => Carbon::now()->addDays(40)->format('Y-m-d'),
                'event_time' => '09:00:00',
                'location' => 'Jakarta International Expo',
                'capacity' => 1000,
                'status' => 'published',
                'approved_by' => $adminUser->id ?? 1,
                'approved_at' => now(),
                'created_by' => $adminUser->id ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'FUTSAL CHAMPIONSHIP',
                'slug' => Str::slug('FUTSAL CHAMPIONSHIP'),
                'description' => 'Kejuaraan futsal antar kampus se-Jabodetabek. Daftarkan timmu sekarang!',
                'event_date' => Carbon::now()->addDays(28)->format('Y-m-d'),
                'event_time' => '07:00:00',
                'location' => 'GOR Futsal Senayan',
                'capacity' => 200,
                'status' => 'published',
                'approved_by' => $adminUser->id ?? 1,
                'approved_at' => now(),
                'created_by' => $adminUser->id ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'ART EXHIBITION: Modern Indonesian Art',
                'slug' => Str::slug('ART EXHIBITION: Modern Indonesian Art'),
                'description' => 'Pameran seni rupa modern dari seniman-seniman Indonesia terbaik. Karya lukisan, patung, dan instalasi.',
                'event_date' => Carbon::now()->addDays(16)->format('Y-m-d'),
                'event_time' => '10:00:00',
                'location' => 'National Gallery Indonesia',
                'capacity' => 500,
                'created_by' => $adminUser->id ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'PHOTOGRAPHY EXHIBITION',
                'slug' => Str::slug('PHOTOGRAPHY EXHIBITION'),
                'description' => 'Pameran fotografi dengan tema "Indonesia dari Berbagai Sudut Pandang". Ratusan karya fotografi memukau!',
                'event_date' => Carbon::now()->addDays(24)->format('Y-m-d'),
                'event_time' => '11:00:00',
                'location' => 'Museum Nasional',
                'capacity' => 300,
                'status' => 'published',
                'approved_by' => $adminUser->id ?? 1,
                'approved_at' => now(),
                'created_by' => $adminUser->id ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'BOOK FAIR & LITERATURE FESTIVAL',
                'slug' => Str::slug('BOOK FAIR & LITERATURE FESTIVAL'),
                'description' => 'Pameran buku terbesar tahun ini dengan diskon hingga 70%. Meet & greet dengan penulis terkenal!',
                'event_date' => Carbon::now()->addDays(19)->format('Y-m-d'),
                'event_time' => '09:00:00',
                'location' => 'Jakarta Convention Center',
                'capacity' => 10000,
                'created_by' => $adminUser->id ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($events as $event) {
            Event::updateOrCreate(
                ['slug' => $event['slug']], // Check if event with this slug exists
                $event // If not, create with these attributes
            );
        }
    }
}
